name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout
        uses: actions/checkout@v4

      # Шаг 2: Установить Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Шаг 3: Установить зависимости и собрать проект
      - name: Install and Build
        run: |
          npm ci
          npm run build

      # Шаг 4: Деплой собранной папки на GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Указываем папку, которую собрал Webpack
          publish_dir: ./dist
